# Custom Language File for Launcher Customizer

[ejs.app]
title = "Cobblemon Academy"

[ejs.landing]
mediaGitHubURL = "https://github.com/LunaFaction/Cobblemon-Academy"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/cobblemonacademy"

[ejs.settings]
sourceGithubLink = "https://github.com/LunaFaction/Cobblemon-Academy"
supportLink = "https://github.com/LunaFaction/Cobblemon-Academy/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR COBBLEMON ACADEMY"
welcomeDescription = "L'aventure Pokémon rencontre Minecraft comme jamais auparavant !"
welcomeDescCTA = "Vous n'êtes plus qu'à quelques clics de CobblemonAcademy."
