[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "ACTUALI"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités..."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajoutez de nouveaux comptes ou gérez les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Connexion automatique au serveur au lancement."
launchDetachedTitle = "Lancer le jeu séparément du launcher."
launchDetachedDesc = "Si le jeu n'est pas lancé séparément, fermer le launcher fermera également le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods obligatoires"
optionalMods = "Mods optionnels"
dropinMods = "Mods à insérer"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activez ou désactivez les shaders. Attention : les shaders nécessitent une configuration puissante pour fonctionner correctement. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner un pack de shaders"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérez la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "La RAM minimale recommandée est de 3 gigaoctets. Définir les mêmes valeurs minimales et maximales peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est vérifié avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options fournies à la JVM lors de l'exécution. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher lui-même."
allowPrereleaseTitle = "Autoriser les mises à jour pré-release."
allowPrereleaseDesc = "Les pré-releases incluent des fonctionnalités nouvelles qui peuvent ne pas être entièrement testées ou intégrées.<br>Ceci sera toujours activé si vous utilisez une version pré-release."
dataDirectoryTitle = "Dossier de données"
selectDataDirectory = "Sélectionner le dossier de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers de jeu et installations Java locales seront stockés dans ce dossier.<br>Les captures d'écran et sauvegardes de mondes sont enregistrées dans le dossier d'instance correspondant à la configuration du serveur."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Consultez les informations et les notes de version de cette version."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Voir les notes de version sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Téléchargez, installez et consultez les mises à jour du launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"


[ejs.waiting]
waitingText = "En attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "RÉUSSI"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter..."
failureTitle = "Erreur lors du lancement"
failureText = "Voir la console (CTRL + Maj + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Analyse des informations système..."
noCompatibleJava = "Aucune installation<br>Java compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une installation Java 64 bits version {major}. Voulez-vous qu'on l'installe pour vous ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Maj + i) pour plus de détails."
javaRequired = "Java est requis<br>pour le lancement"
javaRequiredMessage = 'Une installation valide de Java {major} en 64 bits est nécessaire pour lancer.<br><br>Veuillez consulter notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">guide de gestion Java</a> pour savoir comment installer Java manuellement.'
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Échec de la recherche de la distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé est corrompu, le fichier peut être endommagé."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"


[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur..."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Consultez la console (CTRL + Maj + i) pour plus de détails."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Voir la console (CTRL + Maj + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité des fichiers..."
errorDuringFileVerificationTitle = "Erreur lors de la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement des fichiers"
preparingToLaunch = "Préparation au lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n'a pas pu être téléchargé correctement. En conséquence, le jeu ne peut pas se lancer.<br><br>Pour résoudre ce problème, désactive temporairement ton antivirus et relance le jeu.<br><br>Si tu as le temps, merci de <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">signaler ce problème</a> en indiquant quel antivirus tu utilises. Nous les contacterons pour essayer de résoudre la situation."
doneEnjoyServer = "C'est prêt. Profite du serveur !"
checkConsoleForDetails = "Merci de consulter la console (CTRL + Maj + i) pour plus de détails."

[js.landing.news]
checking = "Vérification des actualités..."

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "En route vers Cobblemon-Academy !"
joined = "Exploration du serveur !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Fichiers exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur s'est produite"
errorMessage = "L'authentification Microsoft a échoué. Merci de réessayer."
okButton = "OK"


[js.settings.mstfLogout]
errorTitle = "Une erreur s'est produite"
errorMessage = "La déconnexion Microsoft a échoué. Merci de réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner le compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le launcher, vous devez être connecté à au moins un compte. Vous devrez vous reconnecter après la déconnexion.<br><br>Êtes-vous sûr de vouloir vous déconnecter ?"
confirmButton = "Je confirme"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner le compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de la suppression<br>du mod Drop-in {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Échec de l'activation/désactivation<br>d'un ou plusieurs mods Drop-in"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de version."


[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-version disponible"
downloadingButton = "Téléchargement en cours..."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher et exécutez le fichier dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour..."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Nous n'avons pas pu authentifier votre compte Microsoft. Merci de réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : Impossible de charger l'index de distribution"
fatalErrorMessage = "Impossible d'établir une connexion avec nos serveurs pour télécharger l'index de distribution. Aucune copie locale n'a pu être chargée.<br><br>L'index de distribution est un fichier essentiel qui fournit les dernières informations sur le serveur. Le launcher ne peut pas démarrer sans lui. Vérifiez votre connexion internet et relancez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de la mise à jour de la connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Sélectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Recherche de mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur lors de la connexion :<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft n'a pas encore de profil Minecraft configuré. Si vous venez d'acheter le jeu ou de le récupérer via le Xbox Game Pass, vous devez configurer votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n'avez pas encore acheté le jeu, vous pouvez également le faire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur lors de la connexion :<br>Aucun compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'est associé à aucun compte Xbox."
xblBannedTitle = "Erreur lors de la connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft provient d'un pays où Xbox Live est indisponible ou interdit."
under18Title = "Erreur lors de la connexion :<br>Autorisation parentale requise"
under18Desc = "Les comptes des utilisateurs de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s'est produite. Consultez la console pour plus de détails."


[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Veuillez signaler cette erreur."

notFoundTitle = "Erreur interne :<br>Introuvable"
notFoundDesc = "Le point de terminaison d'authentification est introuvable. Veuillez signaler ce problème."

accountMigratedTitle = "Erreur lors de la connexion :<br>Compte migré"
accountMigratedDesc = "Vous avez essayé de vous connecter avec un compte migré. Veuillez réessayer en utilisant l'adresse e-mail de votre compte comme identifiant."

invalidCredentialsTitle = "Erreur lors de la connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "L'e-mail ou le mot de passe saisi est incorrect. Veuillez réessayer."

tooManyAttemptsTitle = "Erreur lors de la connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives de connexion ont été effectuées avec ce compte récemment. Veuillez réessayer plus tard."

invalidTokenTitle = "Erreur lors de la connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d'accès fourni est invalide."

tokenHasProfileTitle = "Erreur lors de la connexion :<br>Le jeton a un profil"
tokenHasProfileDesc = "Le jeton d'accès dispose déjà d'un profil attribué. La sélection des profils n'est pas encore implémentée."

credentialsMissingTitle = "Erreur lors de la connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Le nom d'utilisateur/mot de passe n'a pas été fourni ou le mot de passe contient moins de 3 caractères."

invalidSaltVersionTitle = "Erreur lors de la connexion :<br>Version de salt invalide"
invalidSaltVersionDesc = "Version de salt invalide."

unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non supporté"
unsupportedMediaTypeDesc = "Type de média non supporté. Veuillez signaler cette erreur."

accountGoneTitle = "Erreur lors de la connexion :<br>Compte migré"
accountGoneDesc = "Ce compte a été migré vers un compte Microsoft. Veuillez vous connecter avec Microsoft."

unreachableTitle = "Erreur lors de la connexion :<br>Serveur injoignable"
unreachableDesc = "Impossible de joindre les serveurs d'authentification. Vérifiez qu'ils sont en ligne et que vous êtes connecté à Internet."

gameNotPurchasedTitle = "Erreur lors de la connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte avec lequel vous essayez de vous connecter n'a pas acheté de copie de Minecraft. Vous pouvez en acheter une sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."

unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

